#! /bin/bash

echo Running Pandoc...
pandoc \
	--pdf-engine=xelatex \
	--template=cltemplate.tex \
	-s ./coverletter.md \
	-f markdown \
	-t latex \
	-o ./coverletter.pdf
echo Done

# --latex-engine has been removed.  Use --pdf-engine instead.
